challengeevolux/models.py
from sqlalchemy import Column, Integer, String, Text, Boolean, ForeignKey, and_, func
from sqlalchemy.orm import relationship
from database import Base, db_session


class Student(Base):
    __tablename__ = 'student'
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(120), unique=True)
    email = Column(String(120), unique=True)

    challenge_done = relationship("ChallengeDone",
                                  cascade="all, delete-orphan",
                                  passive_deletes=True)

    def __init__(self, name=None, email=None):
        self.name = name
        self.email = email


class Challenge(Base):
    __tablename__ = 'challenge'
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100), nullable=False)
    description = Column(Text, nullable=False)
    result = Column(String(50), nullable=False)

    def __init__(self, name=None, description=None, result=None):
        self.name = name
        self.description = description
        self.result = result

    # Checks if student has finished this Challenge
    def is_done(self, student_id):
        is_current_challenge_done = db_session.query(func.count(ChallengeDone.id)). \
            filter(and_(ChallengeDone.challenge_id == self.id,
                        ChallengeDone.student_id == student_id)).all()

        return True if is_current_challenge_done[0][0] >= 1 else False

    @staticmethod
    def get_next_available(student_id):
        query = Challenge.query.\
            filter(~Challenge.id.in_(
                db_session.query(ChallengeDone.challenge_id).filter(ChallengeDone.student_id == student_id)))

        return query.first()

    @staticmethod
    def get_available(student_id, current_challenge_id):
        query = Challenge.query.\
            filter(and_(~Challenge.id.in_(
                db_session.query(ChallengeDone.challenge_id).filter(ChallengeDone.student_id == student_id)),
                Challenge.id != current_challenge_id))

        return query.all()

class ChallengeDone(Base):
    __tablename__ = 'challenge_done'
    id = Column(Integer, primary_key=True, autoincrement=True)
    student_id = Column(Integer, ForeignKey('student.id'))
    challenge_id = Column(Integer, ForeignKey('challenge.id'))
    result_ok = Column(Boolean, default=False)

    def __init__(self, student_id, challenge_id, result_ok):
        self.student_id = student_id
        self.challenge_id = challenge_id
        self.result_ok = result_ok

challengeevolux/forms.py
# _*_ encoding: utf8 _*_

from wtforms import Form, TextField, TextAreaField, \
    HiddenField, validators


class StudentForm(Form):
    id = HiddenField()
    name = TextField(u'Nome', [validators.Length(min=4)])
    email = TextField(u'E-mail', [validators.Length(min=6)])


class ChallengeForm(Form):
    id = HiddenField()
    name = TextField(u'Nome', [validators.Length(min=4)])
    description = TextAreaField(u'Descrição', [validators.required()])


class ChallengeAdminForm(ChallengeForm):
    result = TextField(u'Resultado', [validators.required()])


class ChallengeSiteForm(ChallengeForm):
    student_id = HiddenField(validators=[validators.required()])

challengeevolux/__init__.py
from flask import Flask
from challengeevolux.database import db_session
from views import admin
from views.admin import students, challenges
from views import site

app = Flask(__name__)

@app.teardown_appcontext
def shutdown_session(exception=None):
    db_session.remove()

app.secret_key = 'OpkoIuhYt67FYghi9u8Yij9u8y7t6fyHjnKLM'

# Admin panel
app.register_blueprint(admin.blueprint)
app.register_blueprint(students.blueprint)
app.register_blueprint(challenges.blueprint)

# Registering Site
app.register_blueprint(site.blueprint)

challengeevolux/views/admin/__init__.py
# _*_ encoding: utf8 _*_

from flask import Blueprint, render_template

blueprint = Blueprint('admin', __name__,
                     url_prefix='/admin',
                     template_folder='templates')

# Default Route
@blueprint.route('/')
def index():
    template_params = {'current_menu': 'index'}

    return render_template('/admin/index.html', **template_params)

challengeevolux/views/site.py
# _*_ encoding: utf8 _*_
from string import strip
from flask import Blueprint, render_template, \
    redirect, url_for, request, flash
from challengeevolux.database import db_session
from challengeevolux.models import Student, Challenge, ChallengeDone

blueprint = Blueprint('site', __name__,
                      template_folder='templates')


@blueprint.route('/')
def index():
    template_params = {'students': Student.query.all()}

    return render_template('/site/index.html', **template_params)


@blueprint.route('/pick_challenge/<student_id>')
def pick_challenge(student_id):
    student = Student.query.get(student_id)

    if not student:
        flash(u'Usuário inválido. Tem certeza que entrou com a url correta?', 'danger')
        return redirect(url_for('site.index'))

    next_challenge = Challenge.get_next_available(student.id)

    if next_challenge:
        return redirect(url_for('site.challenge', challenge_id=next_challenge.id, student_id=student_id))
    else:
        return render_template('/site/challenge_end.html')


@blueprint.route('/challenge/stu_<student_id>/no_<challenge_id>')
def challenge(student_id, challenge_id):
    student = Student.query.get(student_id)
    current_challenge = Challenge.query.get(challenge_id)

    if not student:
        flash(u'Usuário inválido. Tem certeza que entrou com a url correta?', 'danger')
        return redirect(url_for('site.index'))

    if not current_challenge:
        flash(u'Desafio inválido. Tem certeza que entrou com a url correta?', 'danger')
        return redirect(url_for('site.index'))

    if current_challenge.is_done(student.id):
        flash(u'Você já respondeu a esse exercício', 'warning')
        return redirect(url_for('site.index'))

    other_challenges = Challenge.get_available(student.id, current_challenge.id)

    template_params = {'student': student,
                       'challenge': current_challenge,
                       'challenges': other_challenges}

    return render_template('/site/challenge.html', **template_params)


@blueprint.route('/challenge/send', methods=['post'])
def challenge_send():
    student = Student.query.get(request.form['student_id'])
    current_challenge = Challenge.query.get(request.form['challenge_id'])

    if not student:
        flash(u'Usuário inválido. Tem certeza que entrou com a url correta?', 'danger')
        return redirect(url_for('site.index'))

    if not current_challenge:
        flash(u'Desafio inválido. Tem certeza que entrou com a url correta?', 'danger')
        return redirect(url_for('site.index'))

    if current_challenge.is_done(student.id):
        flash(u'Você já respondeu a esse exercício', 'warning')
        return redirect(url_for('site.index'))

    answer = strip(request.form['answer']) == current_challenge.result
    challenge_done_new = ChallengeDone(student.id, current_challenge.id, answer)

    db_session.add(challenge_done_new)
    db_session.commit()

    return redirect(url_for('site.pick_challenge', student_id=student.id))


@blueprint.route('/<path:path>')
def catch_all(path):
    flash(u"Tentasse acessar um recurso indisponível, "
          u"mas esquenta não: te trouxe de volta. :)", 'info')

    return redirect(url_for('site.index'))

challengeevolux/templates/site/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/static/favicon.png">

    <title>{% block title %}Evolux{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <link href="/static/bower_components/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/site/style.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="/static/bower_components/bootstrap/assets/js/html5shiv.js"></script>
      <script src="/static/bower_components/bootstrap/assets/js/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
  </head>

  <body>

    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right black">
          <li {% if current_menu == 'home' %}class="active"{% endif %}><a href="/">Início</a></li>
            <li><a href="/admin">Admin</a></li>
          <li><a href="https://bitbucket.org/joey_ribeiro/challengeevolux" target="_blank">Repositório</a></li>
        </ul>
        <h3>{% block title_h3 %}Desafio Evolux{% endblock %}</h3>
      </div>

      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
             {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  {{ message }}
                </div>
            {% endfor %}
        {% endif %}
      {% endwith %}

      {% block body %}{% endblock %}

      <div class="footer">
        <p>&copy; Evolux 2013</p>
      </div>

    </div> <!-- /container -->

    <script type="text/javascript" src="/static/bower_components/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

challengeevolux/templates/site/challenge.html
{% extends "site/base.html" %}
{% block title %}Evo Challenge{% endblock %}
{% block title_h3 %}Desafio para {{ student.name }}{% endblock %}

{% block css %}
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="/static/bower_components/skulpt/skulpt.min.js"></script>
<script type="text/javascript" src="/static/bower_components/skulpt/skulpt-stdlib.js"></script>
<script type="text/javascript" src="/static/bower_components/ace/build/src-min-noconflict/ace.js"></script>
<script type="text/javascript">
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/chrome");
    editor.getSession().setMode("ace/mode/python");
</script>
<script type="text/javascript">
function outf(text) {
    var mypre = document.getElementById("output");
    mypre.innerHTML = mypre.innerHTML + text;
    $('#modalSend').removeClass('disabled');
    $('#scriptOutput').modal();
}
function builtinRead(x) {
    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined)
            throw "File not found: '" + x + "'";
    return Sk.builtinFiles["files"][x];
}

function runit() {
   var prog = editor.getSession().getValue();
   var mypre = document.getElementById("output");
   mypre.innerHTML = '';
   Sk.pre = "output";
   Sk.configure({output:outf, read:builtinRead});

   try {
      eval(Sk.importMainWithBody("<stdin>",false,prog));
   } catch ( e ) {

    var error_line = e.args.v[2] == undefined ? '' : 'Linha ' + e.args.v[2];
    var error_description = e.args.v[0].v;

    mypre.innerHTML = 'Erro de execução: ' + error_line + ' -> ' + error_description ;
    $('#scriptOutput').modal();
    $('#modalSend').addClass('disabled');
   }
}
</script>
{% endblock %}

{% block body %}

<div class="row">
    <div class="col-lg-12">
        <h3>{{ challenge.name }}</h3>
        <p>{{ challenge.description }}</p>
    </div>
</div>

<div class="row" style="padding-bottom: 20px">
    <div class="{% if challenges %}col-lg-9{% else %}col-lg-12{% endif %}">
        <form>
            <pre id="editor" style="height: 300px"></pre>
            <button type="button" class="btn btn-primary" onclick="runit()">Executar script</button>
        </form>
    </div>

    {% if challenges %}
    <div class="col-lg-3">
        <div class="well sidebar-nav">
            <ul class="nav">
                <li>Desafios restantes</li>
                {% for other_challenge in challenges %}
                    <li><a href="{{ url_for('site.challenge', challenge_id=other_challenge.id, student_id=student.id) }}">{{ other_challenge.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}

</div>
<!-- Modal -->
<div class="modal fade" id="scriptOutput" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form method="post" action="{{ url_for('site.challenge_send') }}">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Execução do Script</h4>
          </div>
          <div class="modal-body">
              <input type="hidden" name="challenge_id" value="{{ challenge.id }}" />
              <input type="hidden" name="student_id" value="{{ student.id }}" />
              <textarea id="output" name="answer" class="form-control" readonly style="resize: none; height: 60px"></textarea>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Voltar</button>
            <button id="modalSend" type="submit" class="btn btn-success">Usar saída do programa como resposta</button>
          </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}

challengeevolux/templates/site/challenge_end.html
{% extends "site/base.html" %}
{% block title %}Evo Challenge{% endblock %}
{% block javascript %}
<script type="text/javascript">
$(function(){
    $('#sucess_message').fadeIn(2500);
});
</script>
{% endblock %}
{% block body %}
<div id="sucess_message" class="jumbotron" style="display: none">
    <h1>Obrigado</h1>
    <p class="lead">Todos os seus desafios foram realizados. Espero que tenha gostado! Que tal checar os fontes desse projeto agora?</p>
    <p><a id="pick_challenge" href="https://bitbucket.org/joey_ribeiro/challengeevolux" target="_blank" class="btn btn-success">Challengeevolux no Bitbucket</a></p>
</div>
{% endblock %}

challengeevolux/templates/site/index.html
{% set current_menu = 'home' %}

{% extends "site/base.html" %}
{% block title %}Evo Challenge{% endblock %}
{% block javascript %}
<script type="text/javascript">
$('#user_select').on('change', function(){
  if ($(this).val())
      $('#pick_challenge').removeClass('disabled');
  else
      $('#pick_challenge').addClass('disabled');
});
$('#pick_challenge').on('click', function(){
   window.location = "/pick_challenge/" + $('#user_select').val();
});
</script>
{% endblock %}
{% block body %}
    <div class="jumbotron">
    <h1>Evochallenge</h1>
    <p class="lead">Selecione seu nome e boa sorte! :)</p>
    <p><select id="user_select" class="form-control" style="width: 300px; margin: 0 auto">
            <option value="">-- Selecione um Herói --</option>
        {% for student in students %}
            <option value="{{ student.id }}">{{ student.name }}</option>
        {% endfor %}
    </select><br /></p>
    <p><a id="pick_challenge" href="javascript:void(0)" class="btn btn-success disabled">Challenge Accepted</a></p>
    </div>

    <div class="row marketing">
    <div class="col-lg-6">
      <h4>Como funciona?</h4>
      <p>Você será levado a uma série de desafios de programação. Selecione seu nome na lista e comece agora!</p>
    </div>

    <div class="col-lg-6">
      <h4>Qual linguagem?</h4>
      <p>Usaremos a linguagem Python para solução dos algorítmos.</p>
    </div>
    </div>
{% endblock %}